# Generated by Django 3.2.3 on 2021-09-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0082_alter_history_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sending', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('mailing_type', models.CharField(choices=[('cancellation', 'Отмена'), ('reminder', 'Напоминание')], max_length=12, verbose_name='Тип сообщения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='api.event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mailings', to='api.event', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рассылка уведомлений',
                'verbose_name_plural': 'Рассылки уведомлений',
                'ordering': ('-date_sending',),
            },
        ),
    ]
