# Generated by Django 3.2.3 on 2021-08-28 06:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_right_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=128, region=None, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
    ]
