# Generated by Django 3.2.3 on 2021-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_event_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Фильмы', 'Фильмы'), ('Куда пойти', 'Куда пойти'), ('Вопросы', 'Вопросы'), ('Права', 'Права'), ('Видеоролики', 'Видеоролики'), ('Календарь', 'Календарь')], max_length=50, verbose_name='Категория'),
        ),
    ]
