# Generated by Django 3.2.3 on 2021-08-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(limit_choices_to={'category': 'Календарь'}, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(limit_choices_to={'category': 'Куда пойти'}, related_name='places', to='api.Tag', verbose_name='Тег(и)'),
        ),
    ]
