# Generated by Django 3.2.3 on 2021-08-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20210828_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled',
            field=models.BooleanField(default=False, help_text='События с этой меткой помечаются как "Отмененные", запись на них становится недоступной.', verbose_name='Отметка об отмене события'),
        ),
    ]
