# Generated by Django 3.2.3 on 2021-08-28 09:06

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_event_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event', validators=[api.validators.event_lifetime_validator, api.validators.free_seats_validator, api.validators.event_canceled_validator]),
        ),
    ]
