# Generated by Django 3.2.3 on 2021-08-28 15:49

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('api', '0078_auto_20210828_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='raw_html',
        ),
        migrations.AddField(
            model_name='catalog',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Отображается под изображением.', max_length=200, null=True, verbose_name='Подпись к изображению'),
        ),
        migrations.AddField(
            model_name='history',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/870/520', help_text='Альтернативный способ загрузки изображения. Приоритет у файла.', max_length=192, verbose_name='Ссылка на изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='lower_body',
            field=martor.models.MartorField(default='Some text', help_text='Текст статьи под слайдером с изображениями. ', verbose_name='Текст статьи под слайдером'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='uper_body',
            field=martor.models.MartorField(default='Some text', help_text='Текст статьи над слайдером с изображениями. Для выделения абзаца используйте блок Quote (Ctrl + Q).', verbose_name='Текст статьи над слайдером'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(help_text='Отображается над основным текстом статьи.', max_length=1024, verbose_name='Верхний абзац'),
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.history', verbose_name='История')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='common.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение истории',
                'verbose_name_plural': 'Изображения истории',
                'ordering': ('order',),
            },
        ),
    ]
