# Generated by Django 3.2.3 on 2021-09-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20210904_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-id',), 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
    ]
