# Generated by Django 3.2.3 on 2021-09-19 11:32

import api.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-id',), 'permissions': (('places_in_all_cities', 'Можно смотреть места всех городов'),), 'verbose_name': 'Куда пойти', 'verbose_name_plural': 'Куда пойти'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', keep_meta=True, null=True, quality=90, size=[1280, 720], upload_to='articles/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
    ]
