# Generated by Django 3.2.3 on 2021-08-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_participant_event'),
        ('account', '0004_customuser_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Обязательное поле для наставника.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curator',
            field=models.ForeignKey(blank=True, help_text='Обязательное поле для наставника.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Выберите эту метку, если пользователь является наставником.', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Обязательное поле для регионального модератора.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.region', verbose_name='Регион'),
        ),
    ]
