# Generated by Django 3.2.3 on 2021-09-19 11:55

import common.validators
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', keep_meta=True, quality=100, size=[1280, 720], upload_to='images/', validators=[common.validators.file_size_validator, common.validators.image_extension_validator], verbose_name='Изображение'),
        ),
    ]
