name: Docker hub update
on:
  push:
    branches: [ Artem ]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Dockerhub

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: t0rk
          password: nemfub-rawdop-9bEsfi
      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: t0rk/bbbs:latest
