name: Docker hub update
on:
  push:
    branches: [ integration ]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Dockerhub

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bbbs:latest

  send_message:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: Send notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "Docker образ обновлен.\n
                  Чтобы загрузить обновление:\n
                  docker pull t0rk/bbbs:latest\n
                  docker-compose stop web\n
                  docker-compose rm web\n
                  docker-compose up -d\n"
